"""Shared company drive for the fictional tenant 'Acme Corp' (demo content)."""
from .db import now

COMPANY_NAME = "Acme Corp"
COMPANY_OWNER = "COMPANY"


def make_pdf(title, lines):
    """Minimal single-page PDF (Helvetica), no external dependencies."""
    def esc(s):
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    ops = ["0.15 0.35 0.75 rg", "0 800 595 42 re f",           # header band
           "BT", "1 1 1 rg", "/F2 13 Tf", "50 815 Td", f"({esc(COMPANY_NAME.upper())}  |  CONFIDENTIAL) Tj", "ET",
           "BT", "0 0 0 rg", "/F2 20 Tf", "50 760 Td", f"({esc(title)}) Tj",
           "/F1 11 Tf", "16 TL", "0 -14 Td"]
    ops += [f"({esc(line)}) '" for line in lines]
    ops += ["ET", "BT", "0.5 0.5 0.5 rg", "/F1 8 Tf", "50 30 Td",
            f"(Generated by the {esc(COMPANY_NAME)} document system. Access to this file is audit-logged.) Tj", "ET"]
    stream = "\n".join(ops).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
    ]
    out, offsets = bytearray(b"%PDF-1.4\n"), []
    for i, obj in enumerate(objects, 1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + obj + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 %d\n0000000000 65535 f \n" % (len(objects) + 1)
    out += b"".join(b"%010d 00000 n \n" % off for off in offsets)
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (len(objects) + 1, xref)
    return bytes(out)


PDFS = [
    ("Finance", "Q3_2026_Financial_Report.pdf", "Q3 2026 Financial Report", [
        "Revenue: $48.2M (+12% QoQ)      Operating margin: 18.4%",
        "Gross profit: $29.7M             EBITDA: $10.1M",
        "", "Highlights",
        "- Enterprise subscriptions grew 21% year over year.",
        "- Cloud infrastructure costs reduced by 7% after vendor renegotiation.",
        "- Cash and equivalents: $112.5M at quarter end.",
        "", "Outlook: Q4 revenue guidance $50M - $52M.",
        "Prepared by: Finance Department    Approved by: CFO"]),
    ("HR", "Employee_Handbook_2026.pdf", "Employee Handbook 2026", [
        "1. Code of conduct - treat colleagues, customers and data with respect.",
        "2. Working hours - core hours 10:00-16:00, hybrid 3 days in office.",
        "3. Leave - 24 days annual leave, 12 days sick leave.",
        "4. Security - never share passwords; report incidents within 1 hour.",
        "5. Data handling - customer data stays in approved systems only.",
        "6. Equipment - laptops are encrypted and centrally managed.",
        "", "Questions: hr@acme.example"]),
    ("Engineering", "System_Architecture_v3.pdf", "System Architecture v3", [
        "Frontend: web app behind CDN and WAF.",
        "API gateway -> microservices (auth, billing, documents, audit).",
        "Audit service: SHA-256 hash chain + Merkle batches, append-only.",
        "Data: PostgreSQL primary + read replica, nightly encrypted backups.",
        "Observability: metrics, traces and centralised logs (90-day retention).",
        "", "Owner: Platform Engineering    Review cycle: quarterly"]),
    ("Engineering", "Incident_Report_INC-1042.pdf", "Incident Report INC-1042", [
        "Severity: SEV-2          Status: Resolved",
        "Detected: 2026-09-14 02:17 UTC     Resolved: 2026-09-14 03:05 UTC",
        "", "Summary: elevated login failures from a single IP range.",
        "Impact: no accounts compromised; 3 users temporarily locked out.",
        "Root cause: credential-stuffing attempt using leaked third-party lists.",
        "Actions: rate limiting tightened, IP range blocked, MFA reminder sent.",
        "", "Evidence: audit log events verified VALID by the provenance engine."]),
    ("Legal", "Mutual_NDA_Template.pdf", "Mutual Non-Disclosure Agreement", [
        "This Agreement is made between Acme Corp and the Counterparty.",
        "", "1. Confidential Information means any non-public business,",
        "   technical or financial information disclosed by either party.",
        "2. Each party shall protect Confidential Information with at least",
        "   reasonable care and use it only for the agreed Purpose.",
        "3. Term: 3 years from the Effective Date.",
        "4. Governing law: as specified in the signature page.",
        "", "Template ID: LEG-NDA-07    Last reviewed: 2026-06-01"]),
]

TEXTS = [
    ("Finance", "Payroll_Oct_2026.csv",
     "employee_id,name,department,gross_salary,status\n"
     "E1001,Asha Verma,Engineering,9200,Paid\nE1002,Daniel Brooks,Finance,8100,Paid\n"
     "E1003,Meera Iyer,HR,6900,Paid\nE1004,Lucas Moreau,Sales,7600,Pending\n"
     "E1005,Kenji Sato,Engineering,9800,Paid\n"),
    ("Finance", "Vendor_Invoices.csv",
     "invoice,vendor,amount,due_date,status\nINV-5531,CloudHost Inc,18450.00,2026-10-15,Open\n"
     "INV-5532,OfficeWorks,1290.50,2026-10-20,Paid\nINV-5533,SecureNet Audit,7600.00,2026-11-01,Open\n"),
    ("Finance", "Budget_2027_Draft.txt",
     "FY2027 budget draft (v0.3)\n\nEngineering   $14.0M\nSales         $9.5M\nMarketing     $4.2M\n"
     "Operations    $3.1M\nSecurity      $2.4M (+30%: audit logging & SOC tooling)\n\nStatus: pending board review."),
    ("HR", "Leave_Policy.txt",
     "Leave Policy\n\n- Annual leave: 24 days per calendar year.\n- Sick leave: 12 days; certificate after 3 days.\n"
     "- Parental leave: 26 weeks (primary), 6 weeks (secondary).\n- Requests go through the HR portal at least 2 weeks ahead."),
    ("HR", "Onboarding_Checklist.md",
     "# Onboarding checklist\n\n- [ ] Sign employment contract and NDA\n- [ ] Collect laptop and security key\n"
     "- [ ] Complete security awareness training\n- [ ] Meet your buddy and manager\n- [ ] Read the Employee Handbook"),
    ("Engineering", "Release_Notes_v2.4.md",
     "# Release 2.4\n\n## New\n- Merkle-batched audit verification\n- Context-forgery detection\n\n"
     "## Fixed\n- Session timeout now logged as Logout\n- Faster hash-chain verification"),
    ("Engineering", "Key_Rotation_Policy.txt",
     "Credential rotation policy\n\n- Service credentials rotate every 90 days.\n- Rotation is automated by the secrets manager.\n"
     "- Never commit credentials to source control.\n- Emergency rotation within 1 hour of suspected exposure."),
    ("Legal", "Data_Retention_Policy.txt",
     "Data retention\n\n- Audit logs: 7 years, tamper-evident storage.\n- Customer records: duration of contract + 2 years.\n"
     "- Access logs: 1 year.\n- Deletion requests handled within 30 days."),
    ("Sales", "Customer_Contracts_Summary.csv",
     "customer,plan,annual_value,renewal_date,owner\nGlobex Industries,Enterprise,240000,2027-01-31,L. Moreau\n"
     "Initech Labs,Business,86000,2026-12-15,L. Moreau\nUmbrella Health,Enterprise,410000,2027-03-01,K. Sato\n"),
    ("Sales", "Q4_Pipeline.txt",
     "Q4 2026 pipeline\n\nCommitted:  $6.8M\nBest case:  $9.2M\nTop deals:\n"
     "  1. Umbrella Health expansion  $1.2M  (negotiation)\n  2. Globex renewal + upsell   $0.6M  (proposal)"),
]


def seed_company_drive(conn):
    if conn.execute("SELECT 1 FROM Documents WHERE owner_id=?", (COMPANY_OWNER,)).fetchone():
        return
    ts = now()
    for folder, name, title, lines in PDFS:
        data = make_pdf(title, lines)
        conn.execute("INSERT INTO Documents (owner_id, folder, name, kind, data, size, updated_at) "
                     "VALUES (?,?,?,?,?,?,?)", (COMPANY_OWNER, folder, name, "pdf", data, len(data), ts))
    for folder, name, content in TEXTS:
        conn.execute("INSERT INTO Documents (owner_id, folder, name, kind, content, size, updated_at) "
                     "VALUES (?,?,?,?,?,?,?)",
                     (COMPANY_OWNER, folder, name, "text", content, len(content.encode()), ts))
